"""Column_city_added_to_jobs

Revision ID: 6fdd7b573369
Revises: ac91ecdd3317
Create Date: 2022-09-12 23:38:59.020153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdd7b573369'
down_revision = 'ac91ecdd3317'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'city')
    # ### end Alembic commands ###
