"""create_db

Revision ID: ac91ecdd3317
Revises:
Create Date: 2022-09-12 23:36:50.542884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac91ecdd3317'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('jobs',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('company_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_published', sa.Date(), nullable=True),
    sa.Column('date_expiring', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_uid'], ['companies.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_jobs_company_uid'), 'jobs', ['company_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_company_uid'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('companies')
    # ### end Alembic commands ###
